# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

_target_: flowdec.backbones.ncsnpp.NCSNpp
image_size: 768
nonlinearity: swish
nf: 128
ch_mult: [1, 1, 2, 2, 2, 2, 2]
num_res_blocks: 2
attn_resolutions: []
bottleneck_attn: True
resamp_with_conv: True
conditional: True
fir: True
fir_kernel: [1, 3, 3, 1]
skip_rescale: True
resblock_type: biggan
progressive: output_skip
progressive_input: input_skip
progressive_combine: sum
init_scale: 0.0
embedding_type: fourier
fourier_scale: 16
dropout: 0.0
num_channels: 4
output_layer_kwargs:
  kernel_size: 3
  bias: False
  padding: same
  padding_mode: zeros